language: rust
rust:
  - nightly
deploy:
  on:
    tags: true
  provider: cargo
  token:
    secure: SPG9j7afkdAqmRYWHst9eBm2dzLCJuElGKO7Yj+o+7c49BO2j9CJ+DUmOWzCX301oDWzApLu6TRZcTpNr25opxP3lWQQrhTKos5fmDMd5xlRy/u4zIyI5XKrejBaR/jcTCKfXBNElhC719kdq4ZiMfuxU2g+I+Ntuz8Ysx3PLPIuEbifHZWDbmzhvZ4IK2yy7wDyrCxgQEih57Rxl8g1Mkavb3lccE63spwjfiU779ZtATsGE2CDbiAHSu9fvWxi9yLP+qbIJZMQvwrdfuBQ9qWha4pZ+SoTWv5aQy5bTzR31DvVOHbhwfQsCOmrZKLsvyhgqWKJpyZgTUM9AR313tCBd7XeV41KU18IXELApu4CJPkh70SgXCVyVVAzUbuJJzHVr+N9AvCK+KMnCKqXUrmHvXwehiEwiwhJufBxbHj8kylBZTAoU1LGYSRM4FRANF0eP/9WnPdKY/fVl8vNWBTPcOxqoz+yTLl1IfaQhei+VpC0o6AeE0IBCSPMN9+Wf3DIqlgHUbZWUc7OqiPVNxWSHscPJS/8NE9MsronZQRLQol+G4kVT05L4rEcOZwlUlfqDv4UWLCBW4UFUzisahTp9r56ZDSwmTKOqkjnoCjdARII9UL5MXWW5IJhTr1ib7nXFGbCSn4qjZtEdNXEyctFA4Rilz9NbxAz/bZjQ1g=
